CREATE TABLE [dwh].[F_SalesOrderHeader] (
    [SalesOrderHeaderID] INT    IDENTITY (1, 1) NOT NULL,
    [SalesOrderID]       INT    NOT NULL,
    [OrderDateID]        INT    NOT NULL,
    [DueDateID]          INT    NOT NULL,
    [ShipDateID]         INT    NOT NULL,
    [SalesPersonID]      INT    NULL,
    [BillAddressID]      INT    NOT NULL,
    [ShipAddressID]      INT    NOT NULL,
    [SubTotal]           MONEY  NOT NULL,
    [TaxAmt]             MONEY  NOT NULL,
    [Freight]            MONEY  NOT NULL,
    [InsertedETLLogID]   BIGINT NOT NULL,
    [UpdatedETLLogID]    BIGINT NOT NULL,
    [Active]             BIT    NOT NULL,
    PRIMARY KEY CLUSTERED ([SalesOrderHeaderID] ASC),
    FOREIGN KEY ([BillAddressID]) REFERENCES [dwh].[D_Address] ([AddressID]),
    FOREIGN KEY ([DueDateID]) REFERENCES [dwh].[D_Date] ([DateID]),
    FOREIGN KEY ([InsertedETLLogID]) REFERENCES [log].[ETLLog] ([ETLLogID]),
    FOREIGN KEY ([OrderDateID]) REFERENCES [dwh].[D_Date] ([DateID]),
    FOREIGN KEY ([SalesPersonID]) REFERENCES [dwh].[D_SalesPerson] ([SalesPersonID]),
    FOREIGN KEY ([ShipAddressID]) REFERENCES [dwh].[D_Address] ([AddressID]),
    FOREIGN KEY ([ShipDateID]) REFERENCES [dwh].[D_Date] ([DateID]),
    FOREIGN KEY ([UpdatedETLLogID]) REFERENCES [log].[ETLLog] ([ETLLogID])
);

